<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 /***************************************
 *         MAGENTO EDITION USAGE NOTICE *
 *****************************************/
 /* This package designed for Magento COMMUNITY edition
 * This extension is only for developers as a technology exchange
 * Based on EasyTestimonial_v1.5.8 by mage-world.com
 * Fixed the bug that when compilation has been enabled, the testimonial tab in the backend will be blank page.
 *****************************************************
 * @category   Cc
 * @package    Cc_Testimonial
 * @Author     Chimy
 */
?>
<script src="<?php echo $this->getSkinUrl('js/testimonial/jquery.cycle.js')?>" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/testimonial/style.css')?>" />

<script type="text/javascript">
   $j = jQuery.noConflict();
   $j(document).ready(function() {
   $j('#slideshow_advance').cycle({
      fx: '<?php echo (Mage::getStoreConfig('cc_testimonial/general/slider')) ? Mage::getStoreConfig('cc_testimonial/general/slider'):''; ?>',
     timeout:  <?php echo (Mage::getStoreConfig('cc_testimonial/general/delay')) ? Mage::getStoreConfig('cc_testimonial/general/delay') : 1000; ?>
	});
});
</script>

<?php $testimonials = $this->getTestimonials(); ?>
<?php
    if($testimonials->count() < 1):
?>
<div class="postWrapper">
<?php echo Mage::helper('testimonial')->__('No Testimonials'); ?>
</div>
<?php
    else:
?>
<div class="postWrapper">
	<div class="box base-mini mini-cart">
		<div class="head">
            <h4><?php echo Mage::helper('testimonial')->__('Testimonials'); ?></h4>
		</div>	
		<div class="content content_test">
			<h1><img src="<?php echo $this->getSkinUrl()?>images/testimonial/icon_top.gif"> </h1>
			<div id="slideshow"> 		
			<?php foreach ($testimonials as $testimonial): ?>
				 <div>
					<font style="font-style:italic"><?php echo $testimonial->getPostContent(); ?></font>
					<p style="float:right; margin-right:0.4em;"><?php echo $testimonial->getClientName();?>
					<?php 
									$allow_Email = Mage::getStoreConfig('cc_testimonial/general/allow_email');
									$allow_address = Mage::getStoreConfig('cc_testimonial/general/allow_address');
									$allow_company = Mage::getStoreConfig('cc_testimonial/general/allow_company');
                                                                        if($allow_Email && $testimonial->getEmail()!=''){
									      echo ' - '.$testimonial->getEmail();
									}
									if($allow_company && $testimonial->getCompany()!='') {?>- <a href="<?php echo $testimonial->getWebsite(); ?>" ><?php echo $testimonial->getCompany();?></a><?php }
									if($allow_address && $testimonial->getAddress()!=''){
										echo ' - '.$testimonial->getAddress();
									}

									?>
									</p>
								</div>
				     
			<?php endforeach; ?>
			</div>
			<h1 class="icon_bt"><img src="<?php echo $this->getSkinUrl()?>images/testimonial/icon_bt.gif"> </h1>
		</div>
		<div class="div_bt_box">
			<h6> 
				<a href="<?php echo Mage::getUrl("testimonial"); ?>">
					<?php echo Mage::helper('testimonial')->__('View All'); ?>
				</a>
			
			</h6>	
		</div>
	</div>
</div>

<?php
    endif;
?>

