<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Points
 * @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>

<div class="aw_points-coupon-box">

    <h4><?php echo $this->__('Coupon Activation') ?></h4>

    <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
        <div>
            <label for="aw_points-coupon">
                <?php echo $this->__('Enter coupon code here:') ?>
            </label>
            <input  type="text" id="aw_points-coupon" name="coupon_code" value=""/>
            <button type="submit" title="<?php echo $this->__('Activate Coupon') ?>" class="form-button">
                <span>
                    <span>
                        <?php echo $this->__('Activate Coupon') ?>
                    </span>
                </span>
            </button>
        </div>
    </form>

</div>

