<?php $_product = $this->getProduct(); ?>
<div class="share-box" >
    <b><?php echo $this->__('Share:') ?></b>
    	
    <div class="facebook">
        <div class="fb-like" data-send="false" data-layout="box_count" data-width="auto" data-show-faces="false"></div>
    </div>	
    			
    <div class="twitter">
        <a href="https://twitter.com/share" class="twitter-share-button" data-count="vertical">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
    </div>
    
    <div class="google">			
        <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
        <g:plusone size="tall"></g:plusone>
    </div>
    
    <div class="share-this">
    	<div class="addthis_toolbox addthis_default_style ">
    		<a href="http://www.addthis.com/bookmark.php?v=250&amp;pubid=xa-4eca4fbc5165f40f" class="addthis_button_compact">Share</a>
    	</div>
    	<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4eca4fbc5165f40f"></script>    	
		<?php if ($this->canEmailToFriend()): ?>
    		<a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>">
    			<img src="<? echo $this->getSkinUrl('groupdeals/images/mail.png') ?>" height="17px" width="16px" /> <?php echo $this->__('Email to a Friend') ?>
    		</a>
		<?php endif; ?>
    </div>
</div>