<?php 
	if (method_exists($this, 'renderCategoriesMenuHtml')){		
		$menu_block = $this;
	}else{
		$menu_block = Mage::getBlockSingleton('mec_navigation/navigation');				
	}
	$_menu = $menu_block->renderCategoriesMenuHtml(0,'level-top');
?>
<?php if($_menu): ?>
    <?php switch ($menu_block->getTypeNavigation()):  
            case Mec_Navigation_Model_Layer::FILTER_TYPE_DROPDOWN: ?>
              <div class="gan-wrapper gan-top">
                  <ul class="gan-dropdown-list">                  
                      <?php echo $_menu ?>          
                  </ul>
              </div>           
           <?php break; ?>           
           <?php case Mec_Navigation_Model_Layer::FILTER_TYPE_PLAIN: ?>
              <div class="gan-wrapper gan-top">
                  <ul id="gan_nav_top" class="gan-plain-list">
                    <?php echo $_menu ?>
                  </ul>
              </div>     
           <?php break; ?> 
           <?php default: ?>
              <div class="nav-container">
                    <ul id="nav">
                        <?php echo $_menu ?>
                    </ul>
              </div>  
    <?php endswitch; ?>
<?php endif ?>
