<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @copyright  Copyright (c) 2009-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div style="display:block; float:right; margin-bottom: 4px;">
    <?php echo $this->__('Inappropriate review?') ?>&nbsp;<a class="abuse-link" link="<?php echo $this->getAbuseUrl() ?>" onclick="reportAbuse(this)"><?php echo $this->__('Report it') ?></a>
</div>