<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Points
 * @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>

<div class="my-account">
	<div class="page-title">
		<h1><?php echo $this->getTitle()?></h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<?php if ($this->hasInvitees()): ?>  
        <fieldset>      
			<table class="data-table" id="invitelist-table">
				<thead>
					<tr>
						<th><?php echo $this->__('E-mail') ?></th>
						<th><?php echo $this->__('Status') ?></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->getCollection() as $item): ?>
						<tr>
							<td>
								<span class="nobr"><?php echo $item->getEmail() ?></span>
							</td>
							<td>
								<span class="nobr"><?php echo $item->getStatus() ?></span>
							</td>
						</tr>
					<?php endforeach ?>
					</tbody>
			</table>
            <script type="text/javascript">decorateTable('invitelist-table')</script>            
		</fieldset>
	<?php else: ?>
		<p><?php echo $this->__("You haven't sent any invitations yet.") ?><br /><br /><?php echo $this->__("Earn Reward Points from sending invitations to your friends!") ?></p>
	<?php endif ?>
	<div class="buttons-set">
        <button  title="<?php echo $this->__('Send invitation') ?>" class="button" onclick="window.location.href='<?php echo $this->getInvitationFormUrl(); ?>'">
			<span>
				<span><?php echo $this->__('Send invitation') ?></span>
			</span>
		</button>
		<p class="back-link"><a href="<?php echo $this->getBackUrl(); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	</div>
</div>