<div id="fb-root"></div>
<script type="text/javascript">
    //<![CDATA[
    window.fbAsyncInit = function() {
        FB.init({
            appId  : <?php echo json_encode($this->getApiKey()) ?>,
            status : true, // check login status
            cookie : true, // enable cookies to allow the server to access the session
            xfbml  : true,  // parse XFBML
            oauth  : true,
            channelUrl : '<?php echo $this->getChannelUrl() ?>'  // custom channel
        });
        Event.fire(window, "facebook:fbAsyncInit");
    };
 
    (function() {
        var e = document.createElement('script');
        e.src = document.location.protocol + '//connect.facebook.net/<?php echo $this->getLocale() ?>/all.js';
        e.async = true;
        document.getElementById('fb-root').appendChild(e);
    }());
 
    document.observe('click', function(e){
        var target = e.findElement('a[rel^=facebook-connect]') || e.findElement('button[rel^=facebook-connect]');
        if (target && target.readAttribute('rel')=='facebook-connect') {
            e.stop();
            try{
                FB.login(function(response){
                    if (response.authResponse){
                        //console.log('Welcome! Fetching your information... ');
                        //console.log(response.status);
                        if(response.status=='connected') { setLocation('<?php echo $this->getConnectUrl() ?>');}
                        else{
                        //console.log('User cancelled login or did not fully authorize.');
                        }
 
                    }
                },
                {scope:<?php echo $this->getRequiredPermissions() ?>});
            }catch(error){}
        }
    });
    //]]>
</script>
