<?php
	/**
	 * aheadWorks Co.
	 *
	 * NOTICE OF LICENSE
	 *
	 * This source file is subject to the EULA
	 * that is bundled with this package in the file LICENSE.txt.
	 * It is also available through the world-wide-web at this URL:
	 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
	 *
	 * @category   AW
	 * @package    AW_Hometabspro
	 * @copyright  Copyright (c) 2010 aheadWorks Co. (http://www.aheadworks.com)
	 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
	 */
?>
<div class="aw-htp-loader" id="htp-loader">
<?php if ($this->showImage()): ?>		
	<img src="<?php echo $this->getImagePath(); ?>" alt="<?php echo $this->getLoaderText(); ?>" />
<?php else: ?>
	<?php echo $this->getLoaderText(); ?>
<?php endif; ?>	
</div>
