<select <?php if($this->ajaxEnabled()):?>onchange="setNavigationUrl( this.value ? this.value : '<?php echo urlencode($this->getRemoveUrl(true));?>')"<?php else:?>onchange="setLocation( this.value ? GanUrl.decode(this.value) : '<?php echo $this->getParentBlock()->getClearUrl(true);?>')"<?php endif;?>>
	<option value=""><?php echo $this->__('Please Select')?></option>
<?php foreach ($this->getItems() as $_item): ?>
    <option value="<?php echo urlencode($_item->getUrl($this->ajaxEnabled()));?>" <?php if($_item->getActive()):?> selected="selected" <?php endif;?>>
        
        <?php echo $_item->getLabel() ?>
        
    	<?php if(!$_item->getActive()):?>
        (<?php echo $_item->getCount() ?>)
        <?php endif;?>
    </option>
<?php endforeach ?>
</select>
