

<div class="header-container">
    <div class="header">
		<div class="nav-cross-shop">
        <?php if ($this->getIsHomePage()):?>
        <h2 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/></a></h2>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
		<div class="right-links">        
		  
		  <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>

			<div class="quick-access">
				<div class="links">


						<?php echo $this->getChildHtml('mec.advancedsearch') ?>
						<?php //echo $this->getChildHtml('topLinks') ?>
						<div class="menu-wishlist-link" id="menuWishlistWrapper">
							<div id="wishlist-li">
								<?php echo $this->getChildHtml('menuwishlistLinks') ?>
							</div>
							<div id="wishlist-content" style="display:none;">
								<?php echo $this->getChildHtml('wishlisttop') ?>
							</div>
						</div>
						
						<div class="menu-cart-link" id="menuCartWrapper">
							<div id="cart-li">
								<?php echo $this->getChildHtml('menucartLinks') ?>
							</div>
							<div id="cart-content" style="display:none;">
								<?php echo $this->getChildHtml('carty_sidebar') ?>
							</div>
						</div>
			
			
				</div>
			</div>
		</div>
		</div>

		<div class="nav-bar-outer">

				
		<?php echo $this->getChildHtml('topMenu') ?>



            </div>
			
		
        <?php echo $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<?php //echo $this->getChildHtml('topMenu') ?>
<!--<div class="home_page_header_block">
<?php echo $this->getChildHtml('home_page_header_block'); ?>
</div>
-->

