<?php
    /**
     * aheadWorks Co.
     *
     * NOTICE OF LICENSE
     *
     * This source file is subject to the EULA
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://ecommerce.aheadworks.com/LICENSE-M1.txt
     *
     * @category   AW
     * @package    AW_Onsale
     * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
     * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
     */
?>
<?php if ($this->isShow()): ?>
<?php $position = $this->getPosition(); ?>

<div id ="category-container-<?php echo $this->getProduct()->getId(); ?>" class="onsale-category-container" onclick="document.location='<?php echo $this->getProduct()->getProductUrl() ?>'" style="<?php print $this->getImageSizeHtml(); ?> background-image: url('<?php print $this->getImageUrl(); ?>');
            <?php if (in_array($position, array('TL', 'TC', 'TR'))): ?>top: 0px;<?php endif; ?>
            <?php if (in_array($position, array('BL', 'BC', 'BR'))): ?>bottom: 0px;<?php endif; ?>">
    <div id="category-onsale-label-<?php echo $this->getProduct()->getId(); ?>" class="<?php echo  $this->getType() ?>-onsale-category-label-text onsale-category-label"><span><?php print $this->getFormatedText() ?></span></div>
</div>
<script type="text/javascript">
<?php $pos = $this->convertPosition($position);?>
    var vposit = '<?php echo $pos['v'];?>';
    var hposit = '<?php echo $pos['h'];?>';
    new PeriodicalExecuter(function(pe<?php echo $this->getProduct()->getId(); ?>) {
        if (typeof($('category-container-<?php echo $this->getProduct()->getId(); ?>')))
            pe<?php echo $this->getProduct()->getId(); ?>.stop();
        onsaleinit('<?php echo $this->getProduct()->getId(); ?>',hposit,vposit);
    }, 0.01);
</script>
<?php endif; ?>
