<?php 
    
    $product = Mage::registry('current_product');    
    $icon_imgs = $this->getIconData($product,"detail");
    
    $base_folder = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$this->base_dir;
    
    foreach ($icon_imgs as $attribute_code => $img_loc) {
           
        $attribute = $product->getResource()->getAttribute($attribute_code);
        if ($attribute)
        {
            $attribute_value = $attribute ->getFrontend()->getValue($product);
        }
?>
        <ul>
           <li style="width: 49%; float: left;"> 
                <img src="<?php echo $base_folder.$attribute_code."/".$img_loc; ?>"/>
                <span><?php echo substr($attribute_value, 0, 15);   ?>  </span>
           </ul>
        </ul>
<?php        
    }
?>
