<?php
	/**
	 * aheadWorks Co.
	 *
	 * NOTICE OF LICENSE
	 *
	 * This source file is subject to the EULA
	 * that is bundled with this package in the file LICENSE.txt.
	 * It is also available through the world-wide-web at this URL:
	 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
	 *
	 * @category   AW
	 * @package    AW_Hometabspro
	 * @copyright  Copyright (c) 2010 aheadWorks Co. (http://www.aheadworks.com)
	 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
	 */
?>
 <?php echo $this->getLoaderHtml(); ?>
<?php 
    $_productCollection=$this->getCollection();

    $this->addColumnCountLayoutDepend('empty', 6);
    $this->addColumnCountLayoutDepend('one_column', 5);
    $this->addColumnCountLayoutDepend('two_columns_left', 4);
    $this->addColumnCountLayoutDepend('two_columns_right', 4);
    $this->addColumnCountLayoutDepend('three_columns', 3);
?>
<?php if($this->getMode()=='list'): ?>
<?php $_iterator = 0; ?>
<div class="listing-type-list catalog-listing" id="hometabspro">
<?php foreach ($_productCollection as $_product): ?>
    <div class="listing-item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
        <?php // Product Image ?>
        <div class="product-image">
            <a href="<?php echo $this->checkUrl($_product->getProductUrl()) ?>" title="<?php echo $this->htmlEscape($_product->getSmallImageLabel()) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
            </a>
        </div>

        <?php // Product description ?>
        <div class="product-shop">
            <h3 class="product-name"><a href="<?php echo $this->checkUrl($_product->getProductUrl()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h3>
            <?php echo $this->getReviewsSummaryHtml($_product) ?>
            <?php 
                if($_product->isGrouped()){
                    $price = Mage::helper('hometabspro')->getGroupedItemPrice($_product->getId());
                    echo '<div class="price-box"><p class="minimal-price"><span class="price-label">Starting at:</span> <span class="price">$'.$price.'</span></p></div>';
                }
            ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="clear"></div>
            <div class="description">
                <?php echo nl2br($_product->getShortDescription()) ?>
                <a href="<?php echo $this->checkUrl($_product->getProductUrl()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><small><?php echo $this->__('Learn More') ?></small></a>
            </div>
        </div>
    </div>
<?php endforeach; ?>
</div>
<?php else: ?>
<?php // Grid Mode ?>
<div class="listing-type-grid products-grid catalog-listing" id="hometabspro">
<?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount() ? $this->getColumnCount() : 3; ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if($i++%$_columnCount==0): ?>
        <ol class="grid-row" id="htp-grid-row">
        <?php endif; ?>
            <li class="item<?php if ( ($i)%$_columnCount == 0): ?> last<?php endif; ?><?php if ( ($i - 1)%$_columnCount == 0): ?> first<?php endif; ?>">
                <p class="product-image">
                    <a href="<?php echo $this->checkUrl($_product->getProductUrl()) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                    </a>
                </p>
                <h3 class="product-name"><a href="<?php echo $this->checkUrl($_product->getProductUrl()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
				<div class="shortDescription" title="<?php echo nl2br($_product->getShortDescription()) ?>">
					<?php echo nl2br($_product->getShortDescription()) ?>
				</div>
				<?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php
                if($_product->isGrouped()){
                    $price = Mage::helper('hometabspro')->getGroupedItemPrice($_product->getId());
                    echo '<div class="price-box"><p class="minimal-price"><span class="price-label">Starting at:</span> <span class="price">$'.$price.'</span></p></div>';
                }
                ?>
                <?php echo $this->getPriceHtml($_product, true) ?>

            </li>
        <?php if($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ol>
        <?php endif; ?>
    <?php endforeach ?>
    <script type="text/javascript">decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);</script>
</div>
<?php endif; ?>
<script type="text/javascript">
var activeTab='<?php echo Mage::getSingleton('core/session')->getActiveTab();?>';if(activeTab){var currentTab=$$('li.active');for(var i=0;i<currentTab.length;i++){$(currentTab[i].id).removeClassName('active')}$(activeTab).addClassName('active')}
</script>