<div class="footer-container">
    <div class="footer">
		<!-- <div class="inner-footer">
			<h2 class="title"><?php // echo $this->__('Your Recent History') ?></h2>
			<?php // echo $this->getChildHtml() ?>
		</div> -->
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footerbanner')->toHtml(); ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml(); ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bottom')->toHtml(); ?>
			<div class="footerbase-shell">
				<div class="footerbase-row">
					<div class="footerbase-addcell"><address><?php echo $this->getCopyright() ?></address></div>
					<div class="footerbase-linkcell">
						<ul>
							<li><a href="https://twitter.com/wireless1online">Follow us on Twitter</a><div class="tw-link-footer">&nbsp;</div>
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="https://www.facebook.com/wireless1online">Like us on Facebook</a><div class="fb-link-footer">&nbsp;</div>
							<!-- <a href="#">Subscribe to RSS Feeds</a>
							<div class="rss-link-footer">&nbsp;</div> --></li>
						</ul>
					</div>
				</div>
			</div>
    </div>
</div>
<script type="text/javascript">
function toggleMemberMenu(flag){var menuContainer=document.getElementById("mMenu");var LoginDiv=document.getElementById("login-div");var LoginA=document.getElementById("login-a");if(menuContainer.style.display=="none"){menuContainer.style.display="block";addClass(LoginA,'active')}else{menuContainer.style.display="none";removeClass(LoginA,'active')}}function hasClass(element,className){var reg=new RegExp('(\\s|^)'+className+'(\\s|$)');return element.className.match(reg)}function addClass(element,className){if(!this.hasClass(element,className)){element.className+=" "+className}}function removeClass(element,className){if(hasClass(element,className)){var reg=new RegExp('(\\s|^)'+className+'(\\s|$)');element.className=element.className.replace(reg,' ')}}
</script>