<?php

/**
* aheadWorks Co.
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://ecommerce.aheadworks.com/LICENSE-M1.txt
*
* @category   AW
* @package    AW_Featured
* @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
* @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
*/
?>
<?php if($this->canDisplay() && $this->getProductsCollection()->getSize() && !$this->getIsEmpty()) : ?>
<?php $_helper = $this->helper('catalog/output') ?>
<?php $_imageQsize = 135 // Maximal image width\height value, pixels ?>
<?php $_onSaleHelper = $this->helper('awfeatured/onsale') ?>
<?php $_abstractBlock = $this->helper('awfeatured')->getAbstractProductBlock() ?>
<div class="awfeatured awafpgrid" id="<?php echo $this->getUniqueBlockId() ?>" style="<?php echo $this->getContainerStyleString() ?>">
    <?php $_i = $_ulOpened = $_ulClosed = 0; ?>
    <?php foreach($this->getProductsCollection() as $_product) : ?>
        <?php if($_i % $this->getItemsPerRow() == 0) : ?>
        <?php $_ulOpened++ ?>
        <ul>
        <!-- row begins -->
        <?php endif ?>
            <li style="width: <?php echo $this->getItemWidth() ?>%">
                <!-- product item begin -->
                <?php $_imageSrc = Mage::helper('awfeatured/images')->getProductImage($_product, $_product->getData('image_id'), $_imageQsize) ?>
                <?php if($_imageSrc) : ?>
                <div class="afp-thumbnail">
                    <?php if($_onSaleHelper->isOnsale()) echo $_onSaleHelper->startOnsale($_product, $_imageQsize) ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_abstractBlock->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <img src="<?php echo $_imageSrc ?>" alt="<?php echo $this->stripTags($_abstractBlock->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <?php if($_onSaleHelper->isOnsale()) echo $_onSaleHelper->endOnsale() ?>
                </div>
                <?php endif ?>
                <?php if($this->getShowProductName()) : ?>
                <div class="awafptitle">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                </div>
                <?php endif ?>
                <?php if($this->getShowDetails()) : ?>
                <div class="afp-details">
                    <?php echo ($_product->getData('short_description')) ?>
                </div>
                <?php endif ?>
                <?php if($this->getShowPrice()) : ?>
                <?php echo $_abstractBlock->getPriceHtml($_product, true) ?>
                <?php endif ?>
                <?php if($this->getShowAddToCartButton()) : ?>
                <div class="afp-addtocart">
                    <?php if($_product->isSaleable()) : ?>
                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="setLocation('<?php echo $_abstractBlock->getAddToCartUrl($_product) ?>')"><div><?php echo $this->__('Add to Cart') ?></div></button></p>
                    <?php else : ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif ?>
                </div>
                <?php endif ?>
                <!-- product item end -->
            </li>
        <?php if(($_i+1) % $this->getItemsPerRow() == 0) : ?>
        <?php $_ulClosed++ ?>
        <!-- row ends -->
        </ul>
        <?php endif ?>
    <?php $_i++ ?>
    <?php endforeach ?>
    <?php if($_ulOpened != $_ulClosed) : ?>
        </ul>
    <?php endif ?>
</div>
<br clear="all" />
<script type="text/javascript">
    var afpGrid<?php echo $this->getUniqueBlockId() ?> = new afpGrid({
        blockId: '<?php echo $this->getUniqueBlockId() ?>'
    });
</script>
<?php endif ?>
