<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">

			<div class="product-shop-left">
			
			<div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
			<!-- add for brand -->
            <h4><?php echo Mage::helper('aitmanufacturers')->getManufacturerLink($_product);?></h4>
            <!-- end -->
			<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
			
			<?php echo $this->getChildHtml('new_alert_urls') ?>

            
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>
        
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
			
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
			
            <?php echo $this->getChildHtml('other');?>

			</div>
			
			<div class="product-shop-right-wrapper">
				<div class="product-shop-right">
					<div class="add-to-box">
						<?php if($_product->isSaleable()): ?>
							<?php echo $this->getChildHtml('righttocart') ?>
						<?php endif; ?>
						
					</div>
				
			
				</div>
				<?php //echo $this->getChildHtml('catalog.compare.sidebar2') ?>

				<div class="share-links">
				<?php echo $this->getChildHtml('alert_urls') ?>

				</div>
			</div>
			
        </div>

        <div class="product-img-box">
		<?php echo $this->getChildHtml('addto') ?>
            <?php echo $this->getChildHtml('media') ?>
        </div>


		<div class="clearer"></div>
		
		
    </form>
    <script type="text/javascript">
var productAddToCartForm=new VarienForm('product_addtocart_form');productAddToCartForm.submit=function(button,url){if(this.validator.validate()){var form=this.form;var oldUrl=form.action;if(url){form.action=url}var e=null;try{this.form.submit()}catch(e){}this.form.action=oldUrl;if(e){throw e}if(button&&button!='undefined'){button.disabled=true}}}.bind(productAddToCartForm);productAddToCartForm.submitLight=function(button,url){if(this.validator){var nv=Validation.methods;delete Validation.methods['required-entry'];delete Validation.methods['validate-one-required'];delete Validation.methods['validate-one-required-by-name'];if(this.validator.validate()){if(url){this.form.action=url}this.form.submit()}Object.extend(Validation.methods,nv)}}.bind(productAddToCartForm);
    </script>
    </div>
	
	<div id="example-one">
        			
        	<ul class="nav">
                <li class="nav-one"><a href="#details" class="current"><?php echo $this->__('Product description')?><span>&nbsp;</span></a></li>
                <li class="nav-two"><a href="#specification" ><?php echo $this->__('Specification')?><span>&nbsp;</span></a></li>
                <li class="nav-three"><a href="#shipping"><?php echo $this->__('Shipping')?><span>&nbsp;</span></a></li>
                <li class="nav-four "><a href="#tag"><?php echo $this->__('Product tags')?><span>&nbsp;</span></a></li>
                <li class="nav-five last"><a href="#download"><?php echo $this->__('Download')?><span>&nbsp;</span></a></li>
            </ul>
        	
        	<div class="list-wrap tab-content" >
        	
        		<div id="details" >
					<?php if ($_product->getShortDescription()):?>
					<div class="short-description">
						<h2><?php echo $this->__('Quick Overview') ?></h2>
						<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
					</div>
					<?php endif;?>
					
					<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
						<div class="box-collateral <?php echo "box-{$alias}"?>">
							<?php if ($title = $this->getChildData($alias, 'title')):?>
							<h2><?php echo $this->escapeHtml($title); ?></h2>
							<?php endif;?>
							<?php echo $html; ?>
						</div>
					<?php endforeach;?>
					
					
        		</div>
        		 
        		 <div id="reviews" class="hide ">
					        <?php echo $this->getChildHtml('product_additional_data') ?>
        		 </div>
        		 
        		 <div id="related" class="hide ">
					        <?php echo $this->getChildHtml('related') ?>
        		 </div>
        		 
        		 <div id="tag" class="hide ">
				
					<?php //echo $this->getChildHtml('upsell_products') ?>
					<?php echo $this->getChildHtml('product_additional_data') ?>
        		 </div>        		 
        		 <div id="download" class="hide ">
					<?php echo $this->__('download place holder')?>
        		 </div>
        		 
        	 </div> <!-- END List Wrap -->
         
         </div> <!-- END Organic Tabs (Example One) -->
			
			
	
	
	<div class="product-collateral">
	    
		<?php echo $this->getChildHtml('related2') ?>
			<?php if($_product->getTypeId() != 'bundle'){ ?>
				<?php echo $this->getChildHtml('boughtTogether') ?>
			<?php }else{ ?>
				<?php //echo $this->getChildHtml('view.related') ?>
				<?php //echo $this->getChildHtml('related2') ?>
			<?php } ?>
        <?php echo $this->getChildHtml('description') ?>
        <?php echo $this->getChildHtml('additional') ?>
		
		<?php echo $this->getChildHtml('upsell_products') ?>
		<?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
		<div class="reviews-block">
		<hr size="1" noshade="noshade" id="product-title-divider">
		<?php //echo $this->getChildHtml('advancedreviews_summary_reviews2') ?>
			<div class="left-reivews">
			
				<?php echo $this->getChildHtml('product_advancedreviews') ?>
				<!--<a href="#review-form" class="createYourOwnReviewTan"><span>add your reviews</span></a>-->
				<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
			</div>
			
			<?php //echo $this->getChildHtml('productquestions') ?>
			
		</div>

      
		
    </div>
</div>

<div id="product-quick-view">
	<div id="qv-inner">
		<div class="qv-content">
				<div class="left-image">
					 <?php
							$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(70).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
							echo $_helper->productAttribute($_product, $_img, 'image');
					?>
				</div>
				<div class="right-content">
				
					<div class="right-content-left">
						<div class="product-name">
							<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
						</div>
						<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
						 <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
					</div>
					<div class="right-content-right">
							<div class="add-to-box">
								<?php if($_product->isSaleable()): ?>
									<?php echo $this->getChildHtml('toptocart') ?>
								<?php endif; ?>
								<?php echo $this->getChildHtml('addto') ?>
							</div>
					</div>

				</div>
		</div>
	</div>
</div>

<script type="text/javascript">
jQuery.noConflict();jQuery(document).ready(function(){jQuery('#rightqty').change(function(){var qty=jQuery('#rightqty').val();jQuery('#topqty').val(qty)});jQuery('#topqty').change(function(){var qty1=jQuery('#topqty').val();jQuery('#rightqty').val(qty1)});jQuery("#qv-inner").hide();if((navigator.userAgent.indexOf('MSIE')>=0)&&(navigator.userAgent.indexOf('Opera')<0)){jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>300){jQuery("#qv-inner").show();jQuery("#qv-inner").addClass("go-to-top");jQuery("#qv-inner").css("go-to-top",jQuery(window).scrollTop())}else{jQuery("#qv-inner").hide()}})}else{jQuery(document).scroll(function(){if(jQuery(document).scrollTop()>300){jQuery("#qv-inner").show();jQuery("#qv-inner").addClass("go-to-top");jQuery("#qv-inner").css("go-to-top",jQuery(document).scrollTop())}else{jQuery("#qv-inner").hide()}})}});

	(function($) {

    $.organicTabs = function(el, options) {
    
        var base = this;
        base.$el = $(el);
        base.$nav = base.$el.find(".nav");
                
        base.init = function() {
        
            base.options = $.extend({},$.organicTabs.defaultOptions, options);
            
            // Accessible hiding fix
            $(".hide").css({
                "position": "relative",
                "top": 0,
                "left": 0,
                "display": "none"
            }); 
            
            base.$nav.delegate("li > a", "click", function() {
            
                // Figure out current list via CSS class
                var curList = base.$el.find("a.current").attr("href").substring(1),
                
                // List moving to
                    $newList = $(this),
                    
                // Figure out ID of new list
                    listID = $newList.attr("href").substring(1),
                
                // Set outer wrapper height to (static) height of current inner list
                    $allListWrap = base.$el.find(".list-wrap"),
                    curListHeight = $allListWrap.height();
                $allListWrap.height(curListHeight);
                                        
                if ((listID != curList) && ( base.$el.find(":animated").length == 0)) {
                                            
                    // Fade out current list
                    base.$el.find("#"+curList).fadeOut(base.options.speed, function() {
                        
                        // Fade in new list on callback
                        base.$el.find("#"+listID).fadeIn(base.options.speed);
                        
                        // Adjust outer wrapper to fit new list snuggly
                        var newHeight = base.$el.find("#"+listID).height();
                        $allListWrap.animate({
                            height: newHeight
                        });
                        
                        // Remove highlighting - Add to just-clicked tab
                        base.$el.find(".nav li a").removeClass("current");
                        $newList.addClass("current");
                            
                    });
                    
                }   
                
                // Don't behave like a regular link
                // Stop propegation and bubbling
                return false;
            });
            
        };
        base.init();
    };
    
    $.organicTabs.defaultOptions = {
        "speed": 300
    };
    
    $.fn.organicTabs = function(options) {
        return this.each(function() {
            (new $.organicTabs(this, options));
        });
    };
    
})(jQuery);


(function($) {
    $(function() {

        $("#example-one").organicTabs();
        
        $("#example-two").organicTabs({
            "speed": 200
        });

    });
	
})(jQuery);

</script>
<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('feedback')->toHtml(); ?>