<?php if($this->canDisplay() && $this->getProductsCollection()->getSize() && !$this->getIsEmpty()) : ?>
<?php $_helper = $this->helper('catalog/output') ?>
<?php $_imageQsize = 156 // Maximal image width\height value, pixels ?>
<?php $_onSaleHelper = $this->helper('awfeatured/onsale') ?>
<?php $_abstractBlock = $this->helper('awfeatured')->getAbstractProductBlock() ?>
<div class="awfeatured awafpgrid" id="<?php echo $this->getUniqueBlockId() ?>" style="<?php echo $this->getContainerStyleString() ?>">
    <?php $_i = $_ulOpened = $_ulClosed = 0; ?>
    <?php foreach($this->getProductsCollection() as $_product) : ?>
        <?php if($_i % $this->getItemsPerRow() == 0) : ?>
        <?php $_ulOpened++ ?>
        <ul>
        <!-- row begins -->
        <?php endif ?>
            <li style="width: <?php echo $this->getItemWidth() ?>%">
                <!-- product item begin -->
                <?php $_imageSrc = Mage::helper('awfeatured/images')->getProductImage($_product, $_product->getData('image_id'), $_imageQsize) ?>
                <?php if($_imageSrc) : ?>
                <div class="afp-thumbnail">
                    <?php if($_onSaleHelper->isOnsale()) echo $_onSaleHelper->startOnsale($_product, $_imageQsize) ?>
                   <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(156,156); ?>" width="156" height="156" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
				   	<?php $product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
					<?php if ($product->getProductIconList() != null && $product->getProductIconList() != 'no_selection'):?>
                    <div class="list-icon"><img src="<?php echo $this->helper('catalog/image')->init($product, 'product_icon_list')->resize(120,155); ?>"/></div>
					<?php endif;?>
                    <?php if($_onSaleHelper->isOnsale()) echo $_onSaleHelper->endOnsale() ?>
                </div>
                <?php endif ?>
				
				<div class="detail-wrapper">
                <?php if($this->getShowProductName()) : ?>

				<?php if(strlen($_product->getName()) <= 40):?>
						<h3 class="product-name"><?php echo $this->htmlEscape($_product->getName()) ?></h3>
					<?php else: ?>
						<h3 class="product-name"><?php echo $this->htmlEscape(mb_substr($_product->getName(),0,40,'UTF-8')) ?></h3>
					<?php endif; ?>
				<a class="view-more" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->__('View More')?></a>
                <?php endif ?>
                <?php if($this->getShowDetails()) : ?>
                <div class="afp-details">
                    <?php echo ($_product->getData('short_description')) ?>
                </div>
                <?php endif ?>
                <?php if($this->getShowPrice()) : ?>
                <?php echo $_abstractBlock->getPriceHtml($_product, true) ?>
                <?php endif ?>
                <?php if($this->getShowAddToCartButton()) : ?>
                <div class="afp-addtocart add-to-cart">
                    <?php if($_product->isSaleable()) : ?>
                    <p><button type="button" title="<?php echo $this->__('c') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_abstractBlock->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy Now') ?></span></span></button></p>
                    <?php else : ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif ?>
                </div>
                <?php endif ?>
                <!-- product item end -->
				</div>
            </li>
        <?php if(($_i+1) % $this->getItemsPerRow() == 0) : ?>
        <?php $_ulClosed++ ?>
        <!-- row ends -->
        </ul>
        <?php endif ?>
    <?php $_i++ ?>
    <?php endforeach ?>
    <?php if($_ulOpened != $_ulClosed) : ?>
        </ul>
    <?php endif ?>
</div>
<br clear="all" />
<script type="text/javascript">
var afpGrid<?php echo $this->getUniqueBlockId()?>=new afpGrid({blockId:'<?php echo $this->getUniqueBlockId() ?>'});
</script>
<?php endif ?>