<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   default_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="block-deals">
<?php $_productCollection=$this->getProductCollection() ?>
<div class="block-title">
        <strong><span>Best Sellers</span></strong>
</div>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>
<?php // Grid Mode ?>
<?php $_collectionSize = $_productCollection->count() ?>
<?php //$_collectionSize = 1; ?>
<?php $_columnCount = 1; ?>
<?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php if ($i++%$_columnCount==0): ?>
	<ul class="list_product_topseller">
        <?php endif ?>
            <li class="topseller_list<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <a class="topseller_img" href="<?php echo $_product->getProductUrl() ?>">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(58, 75); ?>" width="58" height="75" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                    </a>
                   <div class="rankedItemInfo">
						<div class="product-tit">
							<span class="seller-num"><?php echo $this->__($i) ?>.</span>
							<a class="prod_name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a> 
						</div>
						<div class="product_price"><?php echo $this->getPriceHtml($_product, true) ?></div> 
						<div class="shortDescription" title="<?php echo nl2br($_product->getShortDescription()); ?>">
							<?php echo nl2br($_product->getShortDescription()); ?>
						</div>
					</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
	<div class="clear"></div>
	<?php endif ?>
	<?php endforeach ?>
<script type="text/javascript">decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);</script>
<?php endif; ?>
</div>