<div class="recentlyviewed">
<?php
$productViewedBlock = $this->getLayout()->createBlock('reports/product_viewed');
$_collection = $productViewedBlock->getItemsCollection();
$_count = $productViewedBlock->getCount();

if($_count) {
	echo $this->getChildHtml('right.reports.product.viewed');
}else{
//	echo "<strong>";
	echo $this->__('<span><strong id="HistoryColumnTitle">You have no recently viewed items.</strong></span></br><div class="HistoryWrapper"><p>After viewing product detail pages or search results, look here to find an easy way to navigate back to pages you are interested in.</p><div id="rhfUpsellDescription" style="display: none"><p>Look to the right column to find helpful suggestions for your shopping session.</p></div></div>');
//	echo "</strong>";
?>


<?
}
?>
</div>	

