<?php $regionCollection = array(); ?>
<?php $countryId = $this->getRequest()->getParam('country_id', false); ?>
<?php if ($countryId): ?>
	<?php $regionCollection = Mage::getModel('directory/region_api')->items($countryId); ?>
<?php endif; ?>
<?php if (count($regionCollection)>0): ?>
	<select name="region" id="region" class="">
		<option value=""></option>
		<?php foreach ($regionCollection as $region): ?>
		    <?php $regionModel = Mage::getModel('directory/region')->load($region['region_id']); ?>
			<option value="<?php echo $regionModel->getName(); ?>" ><?php echo $regionModel->getName(); ?></option>
		<?php endforeach; ?>
	</select>
<?php else: ?>
	<input type="text" class="input-text required-entry" value="" name="region" id="region">
<?php endif; ?>