<?php $_product = $this->getProduct(); ?>
<?php $now = Mage::getModel('core/date')->timestamp(time()); ?>
<?php $prds = Mage::getModel('core/date')->timestamp($_product->getProductReleaseDate());?>
<?php $buttonTitle = $this->__('Buy Now'); ?>

<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="topqty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
		<?php if($now < $prds && $_product->getProductReleaseDate() != null): ?>
	        	<button type="button" title="<?php echo $this->__('Pre-Order'); ?>" class="button-pre-sml button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $this->__('Pre-Order'); ?></span></span></button>
	        <?php else: ?>
		        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
	        <?php endif; ?>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
